docs: specify Node version requirement to a minor (#7271)
* Update installation.md

I believe the current version of Docusaurus requires node 16.  With 14 I get:
```
import {program} from 'commander';
        ^^^^^^^
SyntaxError: The requested module 'commander' does not provide an export named 'program'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

* Update installation.md

Co-authored-by: Joshua Chen <sidachen2003@gmail.com>